server:
  port: 8080
spring:
  application:
    name: message-service

#  data:
#    mongodb:
#      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}?retryWrites=true&w=majority&appName=chat-app

data:
  mongodb:
    uri:
      mongodb://mongodb:27017/chat-app


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  show-actuator: true

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:4200"
        allowed-methods: "GET"
        allowed-headers: "*"
        allow-credentials: false
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


encryption:
  service:
    base-url: ${ENCRYPTION_SERVICE_BASE_URL:http://localhost:8082/encryption}

notification:
  service:
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8085}

presence:
  service:
    base-url: ${PRESENCE_SERVICE_BASE_URL:http://localhost:8081/presence}

search:
  service:
    base-url: ${SEARCH_SERVICE_BASE_URL:http://localhost:8084/search}

media:
  service:
    base-url: ${MEDIA_SERVICE_BASE_URL:http://localhost:8083/media}