server:
  port: 8080
spring:
  application:
    name: message-service

  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}?retryWrites=true&w=majority&appName=chat-app

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

encryption:
  service:
    base-url: ${ENCRYPTION_SERVICE_BASE_URL:http://localhost:8082/encryption}

notification:
  service:
    base-url: ${NOTIFICATION_SERVICE_BASE_URL:http://localhost:8085/notification}

presence:
  service:
    base-url: ${PRESENCE_SERVICE_BASE_URL:http://localhost:8081/presence}
